// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hyslwljeddgnqrjoxeql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5c2x3bGplZGRnbnFyam94ZXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTIyMDEsImV4cCI6MjA3MjUyODIwMX0.tB4yDnJQw_dSsX2GYFBOcweRB4wYsR8ylEQgnKItOtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);